//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcornPad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeebASM")]
        public global::AcornPad.Common.ExportFormatType Options_Format_1 {
            get {
                return ((global::AcornPad.Common.ExportFormatType)(this["Options_Format_1"]));
            }
            set {
                this["Options_Format_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Decimal")]
        public global::AcornPad.Common.ConversionType Options_Conversion_2 {
            get {
                return ((global::AcornPad.Common.ConversionType)(this["Options_Conversion_2"]));
            }
            set {
                this["Options_Conversion_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Options_Comments_3 {
            get {
                return ((bool)(this["Options_Comments_3"]));
            }
            set {
                this["Options_Comments_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_sprite")]
        public string Character_Name_1 {
            get {
                return ((string)(this["Character_Name_1"]));
            }
            set {
                this["Character_Name_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Row")]
        public global::AcornPad.Common.LayoutType Character_Layout_2 {
            get {
                return ((global::AcornPad.Common.LayoutType)(this["Character_Layout_2"]));
            }
            set {
                this["Character_Layout_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Character_Prefix_3 {
            get {
                return ((bool)(this["Character_Prefix_3"]));
            }
            set {
                this["Character_Prefix_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Four")]
        public global::AcornPad.Common.ColumnType Character_Columns_4 {
            get {
                return ((global::AcornPad.Common.ColumnType)(this["Character_Columns_4"]));
            }
            set {
                this["Character_Columns_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::AcornPad.Common.CompressionType Map_Compression_1 {
            get {
                return ((global::AcornPad.Common.CompressionType)(this["Map_Compression_1"]));
            }
            set {
                this["Map_Compression_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal Map_Columns_2 {
            get {
                return ((decimal)(this["Map_Columns_2"]));
            }
            set {
                this["Map_Columns_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AcornPad_Backdrop_1 {
            get {
                return ((bool)(this["AcornPad_Backdrop_1"]));
            }
            set {
                this["AcornPad_Backdrop_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal Tile_Columns_1 {
            get {
                return ((decimal)(this["Tile_Columns_1"]));
            }
            set {
                this["Tile_Columns_1"] = value;
            }
        }
    }
}
