//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcornPad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeebASM")]
        public global::AcornPad.Common.ExportFormatType Options_Format__1 {
            get {
                return ((global::AcornPad.Common.ExportFormatType)(this["Options_Format__1"]));
            }
            set {
                this["Options_Format__1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Decimal")]
        public global::AcornPad.Common.ConversionType Options_Conversion__2 {
            get {
                return ((global::AcornPad.Common.ConversionType)(this["Options_Conversion__2"]));
            }
            set {
                this["Options_Conversion__2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Options_Comments__3 {
            get {
                return ((bool)(this["Options_Comments__3"]));
            }
            set {
                this["Options_Comments__3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_sprite")]
        public string Character_Name__1 {
            get {
                return ((string)(this["Character_Name__1"]));
            }
            set {
                this["Character_Name__1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Row")]
        public global::AcornPad.Common.LayoutType Character_Layout__2 {
            get {
                return ((global::AcornPad.Common.LayoutType)(this["Character_Layout__2"]));
            }
            set {
                this["Character_Layout__2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Character_Prefix__3 {
            get {
                return ((bool)(this["Character_Prefix__3"]));
            }
            set {
                this["Character_Prefix__3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Four")]
        public global::AcornPad.Common.ColumnType Character_Columns__4 {
            get {
                return ((global::AcornPad.Common.ColumnType)(this["Character_Columns__4"]));
            }
            set {
                this["Character_Columns__4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::AcornPad.Common.CompressionType Map_Compression__1 {
            get {
                return ((global::AcornPad.Common.CompressionType)(this["Map_Compression__1"]));
            }
            set {
                this["Map_Compression__1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal Map_Columns__2 {
            get {
                return ((decimal)(this["Map_Columns__2"]));
            }
            set {
                this["Map_Columns__2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AcornPad_Backdrop__1 {
            get {
                return ((bool)(this["AcornPad_Backdrop__1"]));
            }
            set {
                this["AcornPad_Backdrop__1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal Tile_Columns__1 {
            get {
                return ((decimal)(this["Tile_Columns__1"]));
            }
            set {
                this["Tile_Columns__1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color Character_Left_Selector_5 {
            get {
                return ((global::System.Drawing.Color)(this["Character_Left_Selector_5"]));
            }
            set {
                this["Character_Left_Selector_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Violet")]
        public global::System.Drawing.Color Character_Right_Selector_6 {
            get {
                return ((global::System.Drawing.Color)(this["Character_Right_Selector_6"]));
            }
            set {
                this["Character_Right_Selector_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color Tile_Left_Selector_2 {
            get {
                return ((global::System.Drawing.Color)(this["Tile_Left_Selector_2"]));
            }
            set {
                this["Tile_Left_Selector_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Violet")]
        public global::System.Drawing.Color Tile_Right_Selector_3 {
            get {
                return ((global::System.Drawing.Color)(this["Tile_Right_Selector_3"]));
            }
            set {
                this["Tile_Right_Selector_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color Map_Cross_Selector_3 {
            get {
                return ((global::System.Drawing.Color)(this["Map_Cross_Selector_3"]));
            }
            set {
                this["Map_Cross_Selector_3"] = value;
            }
        }
    }
}
